[metadata]
name = personal-history
version = 0.1.0
author = William Acevedo
description = Personal History Format Implementation
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/wacevedo76/personal_history
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Topic :: Security :: Cryptography
    Topic :: Software Development :: Libraries :: Python Modules

[options]
packages = find:
package_dir =
    = src
python_requires = >=3.8
install_requires =
    cryptography>=42.0.0

[options.entry_points]
console_scripts =
    ph = personal_history.ph.v001.views.cli_view:main

[options.packages.find]
where = src